### ISSUE TITLE
你需要为此应用包安装新证书，或者使用带受信任证书的新应用包。

### ISSUE THREAD

**Issue by hupo376787** [xiaoyaocz/biliuwp#10]
你需要为此应用包安装新证书，或者使用带受信任证书的新应用包。系统管理员或应用开发人员可以提供帮助。已处理证书链，但处理过程因根证书不受信任而终止 (0x800B0109)

![image](https://user-images.githubusercontent.com/14960168/66385765-9fde9500-e9f3-11e9-87db-c723a95dabe6.png)

**Comment by xiaoyaocz** [comment]
直接到应用商店下载安装，或自行生成证书、编译源码使用

**Comment by hupo376787** [comment]
看来只能下载源码，自己搞一个证书了，谢谢
