### ISSUE TITLE
最低版本降低到 14393

### ISSUE THREAD

**Issue by Nukepayload2** [xiaoyaocz/biliuwp#14]
我把项目代码下载下来了，把最低平台 16299 改成 14393，这个应用可以正常列出视频和播放视频。弹幕也正常。为什么把最低平台限制到 16299 呢？

**Comment by Nukepayload2** [comment]
测试的平台：刷了 Win10 ARM 的 Lumia 1520 (系统 Build 版本 15035, 可用 API 情况基本上与 14393 一致)

**Comment by Berrysoft** [comment]
我猜是因为16299才支持.NET Standard 2.0？

**Comment by Nukepayload2** [comment]
这个程序压根没用任何 .net standard 2.0 才有的东西。.net standard 1.4 完全够用了。实在不行为了测试某些 .net standard 1.4 没有的东西可以用共享项目。

**Comment by xiaoyaocz** [comment]
为了后续的更新开发，需要将Microsoft.Toolkit.Uwp等包升级，这些包需要16299起

**Comment by Nukepayload2** [comment]
知道原因了。那么我给个建议。那个工具包主要是提供了一些控件和样式，升级八成是为了 fluent design。那么升级那个控件包前，有两种选择：
1. 先创建一个分支出来，比如说叫v3，然后切换回现在的master分支升级那个包然后开发v4。原先v3的分支无特殊情况就不动了。这样我可以继续在刷了 win10 的 Lumia 手机上正常用这个软件并且我自己能修复一部分问题。
2. 将业务逻辑抽取出来放到另一个类库项目，用新版本的那个库的部分和用旧的那个库的部分拆分成不同的项目。无特殊情况，用旧的那个库的项目不做任何修改。修改后 bilibili3 那个项目会变成一个类库和两个应用程序项目。

**Comment by Nukepayload2** [comment]
要不这样，我现在 Fork，然后我自己维护兼容 14393 的版本。

**Comment by Nukepayload2** [comment]
我自己维护 14393 兼容版本吧。如果别人也有需要的话，[点这里看我维护的14393兼容版](https://github.com/Nukepayload2/biliuwp_14393)
