### ISSUE TITLE
执行时 直接闪退

### ISSUE THREAD

**Issue by yoyosnart** [xiaoyaocz/biliuwp#17]
如题 ,安装完点开应用后等待一段时间 只看得到"自由 富强 民主" 的画面 后来就闪退了

**Comment by themerror** [comment]
1.確認是完整的Windows10
2.如果系統正常，那麼這個是uwp的問題，可以參考一下鏈接先嘗試修復：
https://zhidao.baidu.com/question/1500404424027576179.html
https://jingyan.baidu.com/article/b907e62770697846e6891c44.html
或者直接重新安裝。

**Comment by xiaoyaocz** [comment]
请试下Ver 3.9.63是否还有此问题

**Comment by yoyosnart** [comment]
> 请试下Ver 3.9.63是否还有此问题

您好 , 可以正常开启了！
好奇问下 , 是哪方面的问题导致的呀？

**Comment by xiaoyaocz** [comment]
大概率是样式不兼容

**Comment by yoyosnart** [comment]
好的 謝謝！
