### ISSUE TITLE
Bug Report：評論點讚功能異常

### ISSUE THREAD

**Issue by themerror** [xiaoyaocz/biliuwp#21]
點讚會提示操作失敗（經驗證是成功的，但是會顯示失敗）。如果一直點擊，那麼數字會減一。
具體操作見附件。

**Comment by themerror** [comment]
[1.zip](https://github.com/xiaoyaocz/biliuwp/files/4342756/1.zip)

**Comment by xiaoyaocz** [comment]
fixed
