### ISSUE TITLE
Suggestion:更換或上傳ShanYe MediaPlayer Engine

### ISSUE THREAD

**Issue by themerror** [xiaoyaocz/biliuwp#22]
這個SDK的作者已經刪除了帳戶，uwp版本已無法找到。
![image](https://user-images.githubusercontent.com/46083026/76878965-8b5ecc80-68b0-11ea-9f59-3fbeadde2ed4.png)

**Comment by themerror** [comment]
把引用替換為SYEngine的nuget版[SYEngine.uwp](https://github.com/yunfandev/SYEngine.uwp)？
Not tested.

**Comment by themerror** [comment]
在nuget裡搜索SYEngine可以查到SYEngine.UWP。我試了一下，替換後功能是正常的

**Comment by xiaoyaocz** [comment]
已替换
