### ISSUE TITLE
添加SOCKS5代理设置

### ISSUE THREAD

**Issue by Riajyuu** [xiaoyaocz/biliuwp#30]
在 enbale loopback 之后，现在需要代理软件设置为全局，并不需要实现 SOCKS 代理认证，只需要接入即可

[EnableLoopback.zip](https://github.com/xiaoyaocz/biliuwp/files/4533013/EnableLoopback.zip)

**Comment by xiaoyaocz** [comment]
UWP无法设置代理

**Comment by Riajyuu** [comment]
@xiaoyaocz 用我发的压缩包开启了回环之后就可以的 改一下注册表而已

**Comment by xiaoyaocz** [comment]
UWP应用是无法操作注册表的

**Comment by Riajyuu** [comment]
@xiaoyaocz 不是 我刚刚发的压缩包可以操作注册表 改一下之后任何uwp都可以接入本地回环了。。。
