### ISSUE TITLE
向服务器报告桌面端UA

### ISSUE THREAD

**Issue by Riajyuu** [xiaoyaocz/biliuwp#40]
现在似乎是在使用移动端UA导致账户历史记录当中，通过本客户端生成的记录均被标记为手机观看记录

**Comment by xiaoyaocz** [comment]
由于使用的是Android的API，更改UA可能会引起一些问题

**Comment by themerror** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect

**Comment by themerror** [comment]
這是電腦端的api

**Comment by themerror** [comment]
[播放&下载地址（视频流）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/videostream_url.md)
