### ISSUE TITLE
分P数量大于3时显示不完全

### ISSUE THREAD

**Issue by Riajyuu** [xiaoyaocz/biliuwp#41]
![image](https://user-images.githubusercontent.com/16912240/82333537-6123ab00-99d6-11ea-87e4-eaa9e6d4aa66.png)

此处似乎应该需要额外高度或者滚动条

**Comment by xiaoyaocz** [comment]
![image](https://user-images.githubusercontent.com/16559082/82665687-e91fe400-9c66-11ea-81f2-5cad4dc2bca3.png)
点击此处即可展开分P
