### ISSUE TITLE
微软商店下载错误

### ISSUE THREAD

**Issue by amlkiller** [xiaoyaocz/biliuwp#51]
好吧，这个锅不应该作者背，但是希望作者可以吧新版本发布在GitHub上。
（方便一下魔法上网都下不了的同志qwq）

**Comment by themerror** [comment]
https://store.rg-adguard.net/

**Comment by themerror** [comment]
把商店的網址貼近url，選對應的版本即可

**Comment by themerror** [comment]
https://www.microsoft.com/zh-cn/p/%e5%93%94%e5%93%a9%e5%93%94%e5%93%a9uwp-%e7%ac%ac%e4%b8%89%e6%96%b9/9n7c87236453?activetab=pivot:overviewtab

**Comment by themerror** [comment]
5421.501019FA0C51B_3.9.100.0_neutral_~_wp9dg7z2zqgtj.appxbundle：http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/af83480d-970a-44c6-81db-46107913a726?P1=1607243572&P2=402&P3=2&P4=n8zPXQSmgBiOqdg%2buuFT1s7rqQQiICFENOsXzdWPQ8NkmIxDSgqDBUvvMl3rzJCQGzqjU3SYUi69wLjICmkdPw%3d%3d

**Comment by amlkiller** [comment]
> 5421.501019FA0C51B_3.9.100.0_neutral_〜_wp9dg7z2zqgtj.appxbundle：[http](http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/af83480d-970a-44c6-81db-46107913a726?P1=1607243572&P2=402&P3=2&P4=n8zPXQSmgBiOqdg%2buuFT1s7rqQQiICFENOsXzdWPQ8NkmIxDSgqDBUvvMl3rzJCQGzqjU3SYUi69wLjICmkdPw%3d%3d) ://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/af83480d-970a-44c6-81db-46107913a726?P1 [=](http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/af83480d-970a-44c6-81db-46107913a726?P1=1607243572&P2=402&P3=2&P4=n8zPXQSmgBiOqdg%2buuFT1s7rqQQiICFENOsXzdWPQ8NkmIxDSgqDBUvvMl3rzJCQGzqjU3SYUi69wLjICmkdPw%3d%3d) 1607243572&P2=Q&P=2&P=4&P [％2buuFT1s7rqQQiICFENOsXzdWPQ8NkmIxDSgqDBUvvMl3rzJCQGzqjU3SYUi69wLjICmkdPw％3d％3d](http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/af83480d-970a-44c6-81db-46107913a726?P1=1607243572&P2=402&P3=2&P4=n8zPXQSmgBiOqdg%2buuFT1s7rqQQiICFENOsXzdWPQ8NkmIxDSgqDBUvvMl3rzJCQGzqjU3SYUi69wLjICmkdPw%3d%3d)

点击去没有办法下载诶？这个要怎么下载？

**Comment by amlkiller** [comment]
> 5421.501019FA0C51B_3.9.100.0_neutral_~_wp9dg7z2zqgtj.appxbundle：http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/af83480d-970a-44c6-81db-46107913a726?P1=1607243572&P2=402&P3=2&P4=n8zPXQSmgBiOqdg%2buuFT1s7rqQQiICFENOsXzdWPQ8NkmIxDSgqDBUvvMl3rzJCQGzqjU3SYUi69wLjICmkdPw%3d%3d

谢谢大佬
